<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPybdkui\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPybdkui/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPybdkui.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPybdkui\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPybdkui\appProdProjectContainer([
    'container.build_hash' => 'Pybdkui',
    'container.build_id' => '024bf587',
    'container.build_time' => 1628884330,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPybdkui');
